"""The attribution-footer strip must be narrow enough to keep the guard honest.

`scripts/dev/pr_body_attribution.py` exists so `repo-scope.yml` can clean up a
footer the harness appends after submission, rather than failing every
agent-opened PR on something its author could not prevent.

The risk it carries is over-reach. If the strip is too greedy it becomes a
laundering step: an author pastes a session link into the description, the
workflow quietly removes it, and the guard reports clean on a body that leaked.
So the tests below pin both directions — the footer goes, and everything else
stays and still trips `residual`.
"""

import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts/dev"))

import pr_body_attribution as pba  # noqa: E402

SESSION = "https://claude.ai/code/session_01ABCDEF"
FOOTER = f"_Generated by [Claude Code]({SESSION})_"


def test_strips_footer_with_rule():
    body = f"## What changed\n\nA thing.\n\n---\n{FOOTER}"
    out = pba.analyze(body)
    assert out["stripped"] is True
    assert out["residual"] is False
    assert "A thing." in out["body"]
    assert "claude.ai/code/session" not in out["body"]


def test_strips_footer_without_rule():
    body = f"## What changed\n\nA thing.\n\n{FOOTER}"
    out = pba.analyze(body)
    assert out["stripped"] is True
    assert out["residual"] is False
    assert "claude.ai/code/session" not in out["body"]


def test_body_without_footer_is_untouched():
    body = "## What changed\n\nA thing.\n\n- [x] checklist\n"
    out = pba.analyze(body)
    assert out["stripped"] is False
    assert out["residual"] is False
    assert out["body"] == body


def test_author_written_link_mid_body_is_not_laundered():
    """The whole point: a leak the author wrote must still fail the guard."""
    body = f"## Why\n\nSee {SESSION} for context.\n\nMore prose.\n"
    out = pba.analyze(body)
    assert out["stripped"] is False
    assert out["residual"] is True, (
        "a session link in the body prose must survive the strip so the scope "
        "guard still fails — silently removing it would launder a real leak"
    )


def test_footer_plus_mid_body_link_still_flags_residual():
    """Stripping the footer must not mask a second, author-written link."""
    body = f"## Why\n\nContext at {SESSION}.\n\n---\n{FOOTER}"
    out = pba.analyze(body)
    assert out["stripped"] is True
    assert out["residual"] is True


def test_footer_shaped_line_in_prose_is_left_alone():
    """Prose *about* the footer is not the footer; only a trailing one goes."""
    body = (
        "## Why\n\n"
        f"The harness appends `{FOOTER}` to every PR, which trips the guard.\n\n"
        "That is what this change fixes.\n"
    )
    out = pba.analyze(body)
    assert out["stripped"] is False
    assert out["residual"] is True, (
        "discussing the footer mid-body leaves a real link in the public body; "
        "the guard should still fail and the author should use the escape hatch"
    )


def test_claude_session_trailer_form_counts_as_residual():
    body = "## What\n\nA thing.\n\nClaude-Session: https://example.invalid/x\n"
    out = pba.analyze(body)
    assert out["residual"] is True


def test_empty_body_is_safe():
    out = pba.analyze("")
    assert out["stripped"] is False
    assert out["residual"] is False


def test_cli_status_and_strip_modes_agree():
    body = f"## What changed\n\nA thing.\n\n---\n{FOOTER}"
    script = REPO / "scripts/dev/pr_body_attribution.py"

    status = subprocess.run(
        [sys.executable, str(script), "--status"],
        input=body, capture_output=True, text=True, check=True,
    )
    assert '"stripped": true' in status.stdout
    assert '"residual": false' in status.stdout

    stripped = subprocess.run(
        [sys.executable, str(script)],
        input=body, capture_output=True, text=True, check=True,
    )
    assert "claude.ai/code/session" not in stripped.stdout
    assert "A thing." in stripped.stdout


def test_regex_matches_the_guard_it_serves():
    """Drift guard: the script and repo-scope.yml must agree on what counts.

    If the workflow's grep alternation changes and this one does not, the strip
    could clean something the guard still rejects (or vice versa).
    """
    workflow = (REPO / ".github/workflows/repo-scope.yml").read_text(encoding="utf-8")
    assert "claude\\.ai/code/session|Claude-Session:" in workflow, (
        "repo-scope.yml's session pattern changed — update SESSION_LINK in "
        "scripts/dev/pr_body_attribution.py to match"
    )
