#!/usr/bin/env python3
"""Strip the harness-appended attribution footer from a PR body.

The problem this solves: agent harnesses append a trailing

    ---
    _Generated by [Claude Code](https://claude.ai/code/session_XXXX)_

to the pull-request body *after* the body is submitted. The author cannot
prevent it at creation time, so `repo-scope.yml`'s session-link check fails on
the first run of every agent-opened PR, and the only fix is to hand-edit the
description afterwards.

Harnesses do not all emit the same shape. A second one in current use is a
credit line followed by the bare session URL on its own line:

    🤖 Generated with [Claude Code](https://claude.com/claude-code)

    https://claude.ai/code/session_XXXX

The URL there is neither italic nor markdown-linked, so the original pattern
never saw it. Both shapes are recognised now, and a body carrying both has both
removed — stripping the first exposes the second as the new trailing content.

Silencing that check is the wrong repair — the link would still sit in the
public PR body, which is the exact thing the guard exists to prevent. So this
removes the footer instead, and the workflow writes the stripped body back to
GitHub before linting it. The alarm keeps its meaning; the machine-made mess
gets cleaned up by machine.

**Narrow by construction.** Only a session link inside a trailing attribution
footer is removed. A session link anywhere else in the body was written by the
author, is a real leak, and must still fail the guard — so this reports it
rather than cleaning it.

Usage (body on stdin):
    python3 scripts/dev/pr_body_attribution.py < body.txt        # stripped body -> stdout
    python3 scripts/dev/pr_body_attribution.py --status < body.txt  # JSON verdict -> stdout

Exit codes are always 0; the caller decides what to do with the verdict.
"""
from __future__ import annotations

import argparse
import json
import re
import sys

# The session-attribution pattern the scope guard rejects. Kept identical in
# spirit to repo-scope.yml's grep so the two cannot disagree about what counts.
SESSION_LINK = re.compile(r"claude\.ai/code/session|Claude-Session:", re.IGNORECASE)

# A trailing attribution footer: an optional `---` rule, then a single italic
# "Generated by ..." line carrying a session link. Anchored to the END of the
# body ($ with no trailing content but whitespace) — a footer-shaped line in the
# middle of a description is prose about the footer, not the footer itself, and
# is left alone.
FOOTER = re.compile(
    r"\n*(?:^|\n)-{3,}[ \t]*\n+"          # the --- rule the harness emits
    r"_[^\n]*?claude\.ai/code/session[^\n]*?_[ \t]*\s*$",
    re.IGNORECASE,
)
# Same footer without the rule, for harnesses that omit it.
FOOTER_NO_RULE = re.compile(
    r"\n+_[^\n]*?claude\.ai/code/session[^\n]*?_[ \t]*\s*$",
    re.IGNORECASE,
)
# The credit-line-then-bare-URL shape. Two lines, both required: a line naming
# Claude Code as the generator, then a line that is nothing but the session URL.
# Requiring the credit line is what keeps this narrow — a trailing session URL
# on its own, with no attribution above it, is left in place and still fails the
# guard, because nothing marks it as harness output rather than the author's.
FOOTER_CREDIT_THEN_URL = re.compile(
    r"\n+(?:-{3,}[ \t]*\n+)?"
    r"[^\n]*generated[ \t]+(?:with|by)[^\n]*claude[ \t]+code[^\n]*\n+"
    r"<?https?://[^\s<>]*claude\.ai/code/session[^\s<>]*>?[ \t]*\s*$",
    re.IGNORECASE,
)

FOOTERS = (FOOTER, FOOTER_NO_RULE, FOOTER_CREDIT_THEN_URL)


def strip_footer(body: str) -> tuple[str, bool]:
    """Return (body_without_trailing_attribution_footers, was_stripped).

    Loops rather than stripping once: a harness can append more than one footer
    (the observed case emits the credit-then-URL pair *and* the italic footer),
    and removing the last one is what makes the one before it trailing. Each
    pass strictly shortens the body, so this terminates.
    """
    was_stripped = False
    while True:
        for pattern in FOOTERS:
            stripped = pattern.sub("", body)
            if stripped != body:
                body = stripped.rstrip() + "\n"
                was_stripped = True
                break
        else:
            return body, was_stripped


def analyze(body: str) -> dict:
    """Full verdict for the workflow.

    ``residual`` is the load-bearing field: True means a session link survives
    the strip, i.e. the author wrote one into the body and the guard must fail.
    """
    stripped, was_stripped = strip_footer(body)
    return {
        "stripped": was_stripped,
        "residual": bool(SESSION_LINK.search(stripped)),
        "body": stripped,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--status",
        action="store_true",
        help="emit a JSON verdict instead of the stripped body",
    )
    args = ap.parse_args()

    body = sys.stdin.read()
    verdict = analyze(body)
    if args.status:
        json.dump(
            {"stripped": verdict["stripped"], "residual": verdict["residual"]},
            sys.stdout,
        )
        print()
    else:
        sys.stdout.write(verdict["body"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
