"""
Compute the canonical fingerprint of the shared skills bundle.

`unitares/skills/` is the source of truth (S15-b). The plugin bundle at
`unitares-governance-plugin/skills/` is a byte-identical mirror written by
`scripts/dev/sync-plugin-skills.sh`. The fingerprint is a manifest listing the
sha256 of every skill file plus one aggregate hash; the plugin's CI recomputes
it from its mirrored tree and fails when the two disagree, which catches a
mirror edited by hand instead of re-synced.

The manifest is DERIVED data, so it is generated where it is consumed and is
not committed here. `sync-plugin-skills.sh` writes it into the plugin mirror as
`skills/SKILLS_MANIFEST.sha256`; anything else that needs it computes it on
demand with this script. Until 2026-09-24 unitares committed the file and CI
failed when it was stale. That turned the file into a merge hazard: every pull
request that changed any SKILL.md rewrote the one `# aggregate:` line, and git
treats edits on adjacent per-skill lines as a single conflict, so two PRs
editing two DIFFERENT skills conflicted on the manifest alone (#2361 went
CONFLICTING that way when #2363 merged). GitHub runs no custom merge drivers,
so `.gitattributes` could not help. The path is now in `.gitignore`.

Usage:
    python scripts/dev/skills_manifest.py                      # print the manifest
    python scripts/dev/skills_manifest.py --aggregate          # print only the aggregate hash
    python scripts/dev/skills_manifest.py --output PATH        # write the manifest to PATH
    python scripts/dev/skills_manifest.py --verify PATH        # exit 1 unless PATH matches
    python scripts/dev/skills_manifest.py --skills-dir DIR ... # fingerprint another tree
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILLS_DIR = REPO_ROOT / "skills"
MANIFEST_NAME = "SKILLS_MANIFEST.sha256"

HEADER = (
    "# Canonical fingerprint of unitares/skills/ — generated by\n"
    "# scripts/dev/skills_manifest.py. Do not hand-edit; run the script.\n"
    "# Consumers (e.g. the plugin mirror) verify their copy against this file.\n"
)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# Verification records (scripts/client/_check_freshness.py). Excluded so the
# fingerprint moves only when skill content moves: new attestation files are
# written by every stamping PR. The plugin's parity check excludes the same
# directory.
ATTESTATIONS_DIR = ".attestations"


def _iter_skill_files(skills_dir: Path | None = None) -> list[Path]:
    """All files under the skills tree, sorted, excluding any manifest file
    (a stray local regeneration, or the mirror's own copy) and
    `.attestations/`."""
    root = SKILLS_DIR if skills_dir is None else skills_dir
    files = [
        p
        for p in root.rglob("*")
        if p.is_file()
        and p.name != MANIFEST_NAME
        and ATTESTATIONS_DIR not in p.relative_to(root).parts
    ]
    return sorted(files, key=lambda p: p.relative_to(root).as_posix())


def _lines(skills_dir: Path) -> list[str]:
    return [
        f"{_sha256(path.read_bytes())}  {path.relative_to(skills_dir).as_posix()}"
        for path in _iter_skill_files(skills_dir)
    ]


def build_manifest(skills_dir: Path | None = None) -> str:
    root = SKILLS_DIR if skills_dir is None else skills_dir
    lines = _lines(root)
    aggregate = _sha256("\n".join(lines).encode("utf-8"))
    body = "\n".join(lines)
    return f"{HEADER}# aggregate: {aggregate}\n{body}\n"


def aggregate(skills_dir: Path | None = None) -> str:
    root = SKILLS_DIR if skills_dir is None else skills_dir
    return _sha256("\n".join(_lines(root)).encode("utf-8"))


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Compute the canonical fingerprint of the skills bundle."
    )
    parser.add_argument(
        "--skills-dir", type=Path, default=None,
        help="tree to fingerprint (default: this repository's skills/)",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--aggregate", action="store_true",
                      help="print only the aggregate hash")
    mode.add_argument("--output", type=Path, metavar="PATH",
                      help="write the manifest to PATH")
    mode.add_argument("--verify", type=Path, metavar="PATH",
                      help="exit 1 unless the manifest at PATH matches the tree")
    args = parser.parse_args(argv[1:])

    skills_dir = args.skills_dir if args.skills_dir is not None else SKILLS_DIR
    if not skills_dir.is_dir():
        print(f"ERROR: skills directory missing: {skills_dir}", file=sys.stderr)
        return 1

    expected = build_manifest(skills_dir)

    if args.aggregate:
        print(aggregate(skills_dir))
        return 0

    if args.output is not None:
        args.output.write_text(expected, encoding="utf-8")
        count = len(_iter_skill_files(skills_dir))
        print(f"[skills-manifest] wrote {args.output} ({count} files)")
        return 0

    if args.verify is not None:
        if not args.verify.is_file():
            print(f"[skills-manifest] {args.verify} is missing", file=sys.stderr)
            return 1
        actual = args.verify.read_text(encoding="utf-8")
        if actual == expected:
            count = len(_iter_skill_files(skills_dir))
            print(f"[skills-manifest] {args.verify} matches ({count} files)")
            return 0
        print(f"[skills-manifest] {args.verify} does not match {skills_dir}", file=sys.stderr)
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"on-disk/{args.verify.name}",
            tofile=f"computed/{MANIFEST_NAME}",
            lineterm="",
        )
        print("\n".join(diff), file=sys.stderr)
        return 1

    sys.stdout.write(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
