"""
Publish and verify a canonical fingerprint of the shared skills bundle.

`unitares/skills/` is the source of truth (S15-b). The plugin bundle at
`unitares-governance-plugin/skills/` is meant to be a byte-identical mirror,
but the only sync guard (S15-d) lives in `ship.sh` and is a no-op for any
session that doesn't run `ship.sh` with a local plugin checkout — web/agent
PRs included. Cross-repo CI can't diff the two trees without a PAT, and the
workflow is canonical-first-then-mirror, so a hard cross-repo gate here would
chicken-and-egg.

This script closes the canonical-side half of that gap, the same way
`check-shared-contract.sh` guards AGENTS.md/CLAUDE.md: it commits a manifest
(`skills/SKILLS_MANIFEST.sha256`) listing the sha256 of every skill file plus
one aggregate hash. The CI gate (`--check`) regenerates it from the live tree
and fails if the committed manifest is stale — so the published fingerprint can
never silently lie, and every skill edit surfaces as a reviewable hash change
in the PR diff. The plugin repo (or any consumer) can then verify its mirror by
fetching this one small file, no full checkout or token required.

Usage:
    python scripts/dev/skills_manifest.py            # rewrite the manifest
    python scripts/dev/skills_manifest.py --check     # CI gate: fail on drift
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILLS_DIR = REPO_ROOT / "skills"
MANIFEST_PATH = SKILLS_DIR / "SKILLS_MANIFEST.sha256"
MANIFEST_NAME = MANIFEST_PATH.name

HEADER = (
    "# Canonical fingerprint of unitares/skills/ — generated by\n"
    "# scripts/dev/skills_manifest.py. Do not hand-edit; run the script.\n"
    "# Consumers (e.g. the plugin mirror) verify their copy against this file.\n"
)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _iter_skill_files() -> list[Path]:
    """All files under skills/, sorted, excluding the manifest itself."""
    files = [
        p
        for p in SKILLS_DIR.rglob("*")
        if p.is_file() and p.name != MANIFEST_NAME
    ]
    return sorted(files, key=lambda p: p.relative_to(SKILLS_DIR).as_posix())


def build_manifest() -> str:
    lines: list[str] = []
    for path in _iter_skill_files():
        rel = path.relative_to(SKILLS_DIR).as_posix()
        lines.append(f"{_sha256(path.read_bytes())}  {rel}")
    aggregate = _sha256("\n".join(lines).encode("utf-8"))
    body = "\n".join(lines)
    return f"{HEADER}# aggregate: {aggregate}\n{body}\n"


def main(argv: list[str]) -> int:
    if not SKILLS_DIR.is_dir():
        print(f"ERROR: skills directory missing: {SKILLS_DIR}", file=sys.stderr)
        return 1

    check_only = "--check" in argv[1:]
    expected = build_manifest()

    if not check_only:
        MANIFEST_PATH.write_text(expected, encoding="utf-8")
        count = len(_iter_skill_files())
        print(f"[skills-manifest] wrote {MANIFEST_NAME} ({count} files)")
        return 0

    if not MANIFEST_PATH.exists():
        print(
            f"ERROR: {MANIFEST_NAME} is missing. Run:\n"
            "       python scripts/dev/skills_manifest.py",
            file=sys.stderr,
        )
        return 1

    actual = MANIFEST_PATH.read_text(encoding="utf-8")
    if actual == expected:
        count = len(_iter_skill_files())
        print(f"[skills-manifest] in sync ({count} files)")
        return 0

    print(
        f"ERROR: {MANIFEST_NAME} is stale — skills changed without regenerating "
        "the canonical fingerprint.\n"
        "       Run: python scripts/dev/skills_manifest.py\n"
        "       Then re-sync the plugin mirror: scripts/dev/sync-plugin-skills.sh",
        file=sys.stderr,
    )
    print(file=sys.stderr)
    import difflib

    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=f"committed/{MANIFEST_NAME}",
        tofile=f"actual/{MANIFEST_NAME}",
        lineterm="",
    )
    print("\n".join(diff), file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
