"""Versioned, transport-neutral contract for UNITARES capabilities.

The complete catalog is negotiated through ``list_tools(lite=true)`` and is
callable on every transport.  The default MCP/REST/stdio advertisement is a
progressive subset; omitted names remain callable through ``use_tool`` after
``describe_tool`` supplies their schema.  Operators may request the complete
up-front listing.  The contract therefore fingerprints capabilities, not the
size of one client's initial context.

The contract describes tool reachability and the stable normalized lifecycle
envelope used by product-facing workflow aliases.  It does not claim that a
host installed lifecycle hooks, forwards host events, or honors returned
policy.
"""

from __future__ import annotations

import hashlib
import json
import sys
from typing import Any, Iterable

from mcp.types import Tool

from src.alias_schema import build_alias_input_schema
from src.mcp_compat import get_tool_input_schema
from src.tool_annotations import tool_annotations


INTERFACE_CONTRACT_SCHEMA = "unitares.interface-contract.v1"
# 1.2.0 (2026-09-07): observe gained window_hours / include_calibration and
# describe_tool gained include_schema / include_full_description, the
# parameters their handlers already read; a compatible addition advances the
# negotiated release (docs/INTERFACE_CONTRACT.md).
# 1.4.0 (2026-09-08): parameter descriptions are advertised abridged
# (src/schema_brief.py). No capability, parameter name, type, default or
# requiredness changed — but the descriptions are inside the hashed schema, so
# every input_schema_sha256 moves and a client pinning them needs to know why.
# 1.5.0 (2026-09-08): search_shared_memory stops advertising 14 parameters
# belonging to other actions. Real search filters/provenance stay available;
# ACTION_FIELDS now documents them. The final MCP listing also strips titles
# regenerated by FastMCP, without changing validation or dispatch.
# 1.6.0: one complete catalog for every legacy mode, with unchanged schemas
# and dispatch. Raw names remain available during independent client upgrades.
# 2026-09-11 (no release): the /mcp/ mount advertises the catalog schema
# verbatim instead of FastMCP's lossy regeneration (audit finding F12). No
# capability, name, schema or hash in this contract moved; the transport that
# disagreed with it now agrees.
# 1.7.0 (2026-09-12): cirs_protocol's action description names which
# sub-action each protocol routes (list and status were missing). Its
# input_schema_sha256 moves because descriptions live inside the hashed schema;
# no parameter name, type, default or requiredness changes, and dispatch is
# unchanged. Bumped because a moved digest is what tells a hash-pinning client
# to re-pin (see the re-pin note in docs/INTERFACE_CONTRACT.md), not because
# the catalog gained or lost anything.
# 1.8.0 (2026-09-13): cirs_protocol declares the 24 parameters its selectable
# protocol handlers read, which the MCP argument model dropped before dispatch,
# and limit advertises the handlers' default of 50 in place of null (the null
# reached int() and failed every query action through dispatch). No advertised
# parameter is removed or renamed, the one retyped (limit) stops admitting a null
# that never worked, and only cirs_protocol's
# input_schema_sha256 moves; REST and in-process callers that sent these keys
# with the wrong type or an explicit null now get a validation error, as 1.2.0
# did for observe's include_calibration.
# 1.9.0 (2026-09-13): `complexity` and `confidence` on process_agent_update,
# simulate_update and sync_state advertise their 0-1 bound as JSON Schema
# `minimum`/`maximum` instead of Pydantic's `ge`/`le`, which no client validator
# reads, and their string branch as a regex of numeric strings in [0, 1] instead
# of any string; sync_state's `complexity` also advertises the named levels its
# normalizer accepts, nested inside that string branch. Only the advertised
# schema changes: the fields keep their runtime declaration, so every value is
# accepted or refused as before, with the same validation errors down to each
# error's location, on every transport; three digests move.
# 1.10.0 (2026-09-13): list_tools declares lite, include_advanced and tier,
# which the handler has read since the tool existed (same class as 1.2.0's
# observe/describe_tool gap and 1.8.0's cirs_protocol gap). No advertised
# parameter is removed or renamed; only list_tools' input_schema_sha256 moves.
# 1.11.0 (2026-09-13): knowledge and search_shared_memory declare
# agent_id_filter, which the search handler already honors. Search action
# discovery exposes it too; search_knowledge_graph also records its clarified
# filter description. This compatible addition follows the 1.10.0
# list_tools wire correction.
# 1.12.0 (2026-09-19): dialectic declares judgment_formed on antithesis and
# synthesis. Unlike 1.10.0 and 1.11.0, which advertised parameters the handler
# already read, this one is NEW behavior: set false, the server records an
# abstention and refuses to file the verdict instead of consuming the session's
# reviewer slot. Omitting it is the prior behavior exactly -- the default is
# true, so no existing caller changes and nothing is removed or renamed. Only
# dialectic's input_schema_sha256 and the surface digest move.
# 1.13.0 (2026-09-20): add use_tool and separate the complete negotiated
# capability catalog from the default progressive transport advertisement.
# Every full-catalog capability remains discoverable through list_tools,
# inspectable through describe_tool and callable through use_tool; full schema
# advertisement remains available with UNITARES_TOOL_ADVERTISEMENT=full.
# 1.14.0 (2026-09-24): agent gains action="release_presence", which releases
# the caller's own presence lease at a clean exit. Nothing is removed or
# renamed; agent's input_schema_sha256 and the surface digest move.
# 1.15.0 (2026-09-24): get_governance_metrics and check_working_state declare
# verbosity ("minimal" | "standard" | "full"), which the handler has read since
# the tiers existed (same class as 1.10.0's list_tools gap). Only lite was
# declared, so /mcp/ dropped verbosity and the middle tier was unreachable
# there. Nothing is removed or renamed and verbosity overrides lite when set.
# Behavior that changes for existing inputs: validated routes (/mcp/ and REST
# check_working_state) now refuse an off-list verbosity ("Standard", "bogus")
# that they used to pass through and ignore, as 1.8.0 did for cirs_protocol.
# Handler and envelope now resolve the tier through one function, so an
# explicit lite=null serves minimal (the default), not full; and on the one
# unvalidated route, REST get_governance_metrics, strings the schema reads as
# false ("False", "no", "off", "0", ...) now serve full instead of minimal, as
# every validated route already did. Both tools' input_schema_sha256 and the
# surface digest move.
INTERFACE_CONTRACT_VERSION = "1.15.0"
LIFECYCLE_ENVELOPE_SCHEMA = "unitares.lifecycle-envelope.v1"
SUPPORTED_MCP_SPECIFIER = ">=1.26.0,<3.0.0"
FEDERATION_LIFECYCLE_CAPABILITIES = (
    "start_session",
    "sync_state",
    "check_working_state",
    "record_result",
)
LIFECYCLE_SUCCESS_REQUIRED_FIELDS = (
    "success",
    "tool",
    "next_action",
)
PUBLIC_TRANSPORTS = (
    "mcp_streamable_http",
    "rest_v1_tools",
    "stdio",
)


def workflow_alias_names_for_mode(mode: str) -> tuple[str, ...]:
    """Workflow aliases advertised directly in ``mode``."""
    from src.mcp_handlers.tool_stability import AGENT_WORKFLOW_ALIASES
    from src.tool_modes import get_tools_for_mode

    allowed = get_tools_for_mode(mode)
    return tuple(name for name in AGENT_WORKFLOW_ALIASES if name in allowed)


def build_alias_tool_definition(
    alias_name: str,
    *,
    definitions: Iterable[Tool] | None = None,
) -> Tool:
    """Build the public Tool definition for one workflow alias."""

    from src.mcp_handlers.tool_stability import resolve_tool_alias
    from src.tool_schemas import get_tool_definitions

    actual_name, alias = resolve_tool_alias(alias_name)
    if alias is None:
        raise KeyError(f"{alias_name!r} is not a registered workflow alias")

    raw_definitions = list(definitions or get_tool_definitions())
    actual = next(
        (tool for tool in raw_definitions if tool.name == actual_name),
        None,
    )
    if actual is None:
        raise KeyError(
            f"workflow alias {alias_name!r} targets missing tool {actual_name!r}"
        )

    schema = get_tool_input_schema(actual, {}) or {}
    schema = build_alias_input_schema(
        alias_name,
        schema,
        inject_action=bool(alias.inject_action),
    )
    description = alias.migration_note or f"Alias for {actual_name}"
    # An alias is annotated in its own right rather than inheriting the
    # implementation tool's hints: it narrows the schema, and a router alias
    # pins one action, so its side effects are a subset of what the router as a
    # whole can do (search_shared_memory is read-only; knowledge is not).
    return Tool(
        name=alias_name,
        description=description,
        inputSchema=schema,
        annotations=tool_annotations(alias_name),
    )


def mounted_tool_names() -> set[str] | None:
    """Names the running server will actually dispatch, or None if nothing is mounted.

    ``tools/list`` serves FastMCP's mounted table; this module builds the
    federation contract from the decorator registry. The two are reconciled
    exactly once, by ``auto_register_all_tools`` in
    ``services/mcp_server_bootstrap``. Anything that registers AFTER that is
    counted and never dispatchable — an advertised capability the server
    refuses to serve.

    Measured 2026-09-09: a deep-health probe imported a plugin package five
    seconds after startup, taking a server from 50 advertised / 50 counted to
    50 advertised / 51 counted, and calling the 51st returned "Unknown tool".
    ⛔The plugin flag is only ONE route in. The same state is reachable with
    plugins enabled whenever the entry point is not discovered but the package
    is importable (no metadata, a stale egg-info, a ``register()`` that raised
    and was swallowed) — because ``mcp_server_bootstrap`` remounts only when a
    plugin actually loaded. Fixing callers one at a time cannot close that;
    refusing to advertise what is not mounted can.

    Returns None rather than an empty set when no server module has been
    imported, so a bare import — the flag/index generators, a unit test,
    ``python -m src.interface_contract`` — keeps describing the registry
    exactly as it did before. Reads ``sys.modules`` instead of importing the
    server, so this never creates an import cycle and never starts anything.
    """
    server_module = sys.modules.get("src.mcp_server")
    mcp = getattr(server_module, "mcp", None) if server_module else None
    manager = getattr(mcp, "_tool_manager", None)
    tools = getattr(manager, "_tools", None)
    if not tools:
        return None
    return set(tools)


def get_public_tool_definitions(
    mode: str = "full",
    *,
    client_type: str | None = None,
    include_unmounted: bool = False,
) -> list[Tool]:
    """Return the exact advertised tool surface for a transport and mode.

    Direct transport advertisement is narrowed to the mounted table when a
    server has mounted one. ``include_unmounted`` instead returns the live,
    visible handler catalog used by ``list_tools`` and ``use_tool``: those
    handlers remain reachable through the gateway even when they registered
    after the transport table mounted. See ``mounted_tool_names``.
    """

    # Importing the package settles every @mcp_tool decorator before the
    # registry is read. This is idempotent in long-running servers. Refreshing
    # also picks up entry-point plugins loaded after the package snapshot.
    import src.mcp_handlers as handlers

    from src.mcp_handlers.decorators import (
        get_tool_description,
        get_tool_registry,
        is_tool_hidden,
    )
    from src.tool_modes import should_include_tool
    from src.tool_schemas import get_tool_definitions

    if include_unmounted:
        handlers.refresh_tool_handlers_from_registry()
    definitions = list(get_tool_definitions())
    registered = (
        set(handlers.TOOL_HANDLERS)
        if include_unmounted
        else set(get_tool_registry())
    )
    public: dict[str, Tool] = {}

    for tool in definitions:
        if tool.name not in registered or is_tool_hidden(tool.name):
            continue
        if (
            include_unmounted and mode == "full"
        ) or should_include_tool(tool.name, mode=mode, client_type=client_type):
            public[tool.name] = tool

    from src.mcp_handlers.tool_stability import resolve_tool_alias

    alias_names = workflow_alias_names_for_mode(mode)
    for alias_name in alias_names:
        implementation, _ = resolve_tool_alias(alias_name)
        if is_tool_hidden(alias_name) or is_tool_hidden(implementation):
            continue
        try:
            public[alias_name] = build_alias_tool_definition(
                alias_name,
                definitions=definitions,
            )
        except KeyError:
            # Some introspection tests and embedded consumers deliberately
            # install a partial schema catalog. Direct advertisement skips an
            # alias whose implementation schema is unavailable. The gateway
            # catalog still includes the dispatchable workflow name with an
            # open fallback schema so its negotiated names and contract hash
            # remain the same live set.
            if not include_unmounted:
                continue
            _, alias_info = resolve_tool_alias(alias_name)
            public[alias_name] = Tool(
                name=alias_name,
                description=(
                    alias_info.migration_note if alias_info is not None else ""
                ),
                inputSchema={
                    "type": "object",
                    "properties": {},
                    "additionalProperties": True,
                },
            )

    # A late plugin can register a handler before its optional schema package
    # is visible, and embedded hosts deliberately exercise partial catalogs.
    # The gateway still accepts such public handlers, so negotiate an open
    # schema instead of omitting their name. Hidden handlers remain internal.
    if include_unmounted:
        for tool_name in sorted(registered):
            if tool_name in public or is_tool_hidden(tool_name):
                continue
            if mode != "full" and not should_include_tool(
                tool_name, mode=mode, client_type=client_type
            ):
                continue
            public[tool_name] = Tool(
                name=tool_name,
                description=get_tool_description(tool_name) or f"Tool: {tool_name}",
                inputSchema={
                    "type": "object",
                    "properties": {},
                    "additionalProperties": True,
                },
            )

    # Workflow names are the product-facing path and belong at the top of
    # bounded CLI/discovery output. Preserve the canonical schema-catalog order
    # after them so this seam does not regress existing orientation UX.
    ordered_names = [name for name in alias_names if name in public]
    ordered_names.extend(
        tool.name
        for tool in definitions
        if tool.name in public and tool.name not in alias_names
    )
    ordered_names.extend(
        name for name in sorted(public)
        if name not in ordered_names
    )

    # Never advertise what dispatch would refuse. Narrowing happens last so it
    # cannot reorder the surface, and only when a server has actually mounted a
    # table — see mounted_tool_names() for why this is not the same as the
    # registry, and for the measurement that motivated it.
    mounted = mounted_tool_names()
    if mounted is not None and not include_unmounted:
        ordered_names = [name for name in ordered_names if name in mounted]

    return [public[name] for name in ordered_names]


def _capability_record(tool: Tool) -> dict[str, Any]:
    from src.mcp_handlers.tool_stability import resolve_tool_alias

    implementation, alias = resolve_tool_alias(tool.name)
    input_schema = get_tool_input_schema(tool, {}) or {}
    try:
        schema_bytes = json.dumps(
            input_schema,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    except (TypeError, ValueError):
        # Embedded hosts can expose a dispatchable handler before its schema
        # object has settled. Match the gateway's open-schema fallback rather
        # than dropping the capability or failing the whole negotiation.
        input_schema = {
            "type": "object",
            "properties": {},
            "additionalProperties": True,
        }
        schema_bytes = json.dumps(
            input_schema,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    return {
        "name": tool.name,
        "implementation": implementation,
        "kind": "workflow_alias" if alias is not None else "canonical_tool",
        "input_schema_sha256": hashlib.sha256(schema_bytes).hexdigest(),
        "transport_names": {
            transport: tool.name for transport in PUBLIC_TRANSPORTS
        },
    }


def build_interface_contract(mode: str = "full") -> dict[str, Any]:
    """Build the complete deterministic capability contract.

    ``mode`` is retained for callers from the pre-1.13 API.  Advertisement
    mode never changes federation capability identity.
    """

    capabilities = [
        _capability_record(tool)
        for tool in get_public_tool_definitions("full", include_unmounted=True)
    ]
    canonical = json.dumps(
        capabilities,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return {
        "schema": INTERFACE_CONTRACT_SCHEMA,
        "version": INTERFACE_CONTRACT_VERSION,
        "scope": "tool_surface_and_lifecycle_envelopes",
        "mode": "full",
        "advertisement": {
            "default_mode": "progressive",
            "full_mode_env": {
                "name": "UNITARES_TOOL_ADVERTISEMENT",
                "value": "full",
            },
            "progressive_entrypoints": [
                "list_tools",
                "describe_tool",
                "use_tool",
            ],
        },
        "transports": list(PUBLIC_TRANSPORTS),
        "surface_sha256": hashlib.sha256(canonical).hexdigest(),
        "capabilities": capabilities,
        "federation": {
            "negotiation": {
                "tool": "list_tools",
                "arguments": {"lite": True},
                "contract_path": "interface_contract",
                "capabilities_path": "tools[*].name",
            },
            "mcp": {
                "version_specifier": SUPPORTED_MCP_SPECIFIER,
                "tested_majors": [1, 2],
                "newest_in_range_ci": "blocking",
            },
            "lifecycle": {
                "schema": LIFECYCLE_ENVELOPE_SCHEMA,
                "capabilities": list(FEDERATION_LIFECYCLE_CAPABILITIES),
                "success_envelope": {
                    "required": list(LIFECYCLE_SUCCESS_REQUIRED_FIELDS),
                    "constants": {"success": True},
                    "field_types": {
                        "success": "boolean",
                        "tool": "string",
                        "next_action": "string_or_object",
                        "state_summary": "object",
                        "risk_summary": "string",
                        "memory_suggestions": "array",
                        "recovery_hint": "string_or_object",
                        "raw_governance": "object",
                    },
                    "optional_fields_may_be_omitted": True,
                },
                "failure_envelope": {
                    "required": ["success"],
                    "constants": {"success": False},
                    "detail_fields_any_of": ["error", "message"],
                },
            },
        },
        "limits": {
            "lifecycle_automation": "not_implied",
            "host_event_capture": "not_implied",
            "policy_actuation_outside_governed_writes": "not_implied",
        },
    }


def get_interface_contract_summary(mode: str = "full") -> dict[str, Any]:
    contract = build_interface_contract(mode)
    return {
        "schema": contract["schema"],
        "version": contract["version"],
        "mode": contract["mode"],
        "surface_sha256": contract["surface_sha256"],
        "capability_count": len(contract["capabilities"]),
        "transports": contract["transports"],
        "scope": contract["scope"],
        "federation": contract["federation"],
        "advertisement": contract["advertisement"],
    }


if __name__ == "__main__":
    print(json.dumps(build_interface_contract(), indent=2))
